-- Created by Ebean DDL
-- To stop Ebean DDL generation, remove this comment (both lines) and start using Evolutions

-- !Ups

-- apply changes
create table category (
  id                            bigint generated by default as identity not null,
  active                        boolean default false not null,
  name                          varchar(50) not null,
  code                          varchar(3) not null,
  description                   varchar(255),
  constraint uq_category_name unique (name),
  constraint uq_category_code unique (code),
  constraint pk_category primary key (id)
);

create table product (
  id                            bigint generated by default as identity not null,
  stock                         integer not null,
  category_id                   bigint not null,
  price                         decimal(9,2) not null,
  name                          varchar(100) not null,
  sku                           varchar(20) not null,
  constraint uq_product_sku unique (sku),
  constraint pk_product primary key (id)
);

-- foreign keys and indices
create index ix_product_category_id on product (category_id);
alter table product add constraint fk_product_category_id foreign key (category_id) references category (id) on delete restrict on update restrict;


-- !Downs

-- drop all foreign keys
alter table if exists product drop constraint if exists fk_product_category_id;
drop index if exists ix_product_category_id;

-- drop all
drop table if exists category cascade;

drop table if exists product cascade;

